version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "simple-api"
          ContainerPort: 80
Hooks:
  - AfterAllowTestTraffic: "CodeDeployHook_-blue-green-fargate-_pre-traffic-hook"
